#!/bin/sh
# 90-generate-cors.sh — build the $CORS_ALL_ALLOWED_DOMAIN map from env.
# Runs from /docker-entrypoint.d/ before nginx starts. Output is overwritten
# on every start; edit .env (CORS_BASE_DOMAINS / CORS_EXTRA_ORIGINS), not output.
# Everything runs in a subshell so `set -eu` never leaks into the entrypoint.
(
set -eu
OUT="${CORS_MAP_OUTPUT:-/etc/nginx/cors.d/cors-map.conf}"
BASES="${CORS_BASE_DOMAINS:-}"
EXTRA="${CORS_EXTRA_ORIGINS:-}"

escape_dots() {
    printf '%s' "$1" | sed 's/\./\\./g'
}

{
    echo '# AUTO-GENERATED by 90-generate-cors.sh — do not edit.'
    echo 'map $http_origin $CORS_ALL_ALLOWED_DOMAIN {'
    echo '    default "";'
    # shellcheck disable=SC2086
    for d in $BASES; do
        [ -n "$d" ] || continue
        esc=$(escape_dots "$d")
        printf '    "~^https://([a-z0-9-]+\\.)*%s$" $http_origin;\n' "$esc"
    done
    # shellcheck disable=SC2086
    for o in $EXTRA; do
        [ -n "$o" ] || continue
        printf '    "%s" $http_origin;\n' "$o"
    done
    echo '}'
} > "$OUT"

# Surface config errors early in container logs (main process still decides).
nginx -t 2>&1 | head -5 || true
)
